
version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: nodejs
    container_name: nodejs
    restart: always
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --email vyshnavpcnaravoor@gmail.com --agree-tos --no-eff-email --staging -d backend.dailydevdoubts.site  -d www.backend.dailydevdoubts.site 

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
